export * from "./createStore"
export * from "./remotehq"
export * from "./storedItem"
export * from "./storeType"
export * from "./helpers"
export * from "./types"
export * from "./sequenceHandler"
export * from "./ProcessStatusManager"
export * from "./context"
export * from "./editContext"
export * from "./Forms"
export * from "./classes"
import { addStore } from "./createStore"

export const {
    dumpSchema,
    getSchema,
    getSchemaArray,
    getSchemaArrayAlpha,
    createEditContext,
    removeEditContext,
    getContext,
    userChanged,
    registerDataType,
    registerSingleItem,
    registerSingleUserItem,
    instanceItem,
    instanceNewItem,
    init,
    save,
    registerOnChange,
    registerOnSave,
    registerOnDelete,
    getStoreTypeByName,
    clearAllStoreCache,
    clearStoreCache,
    removeOnChange,
    removeOnRetrieve,
    removeOnSave,
    removeOnDelete,
    getAllStoreTypes,
    setItem,
    storeData,
    getAll,
    requestLoad,
    getItem,
    itemByKey,
    getPropertyArray,
    updateItemNewUser,
    getAccessToken,
    accessTokenSync,
    fetchDataAuthorised,
    sendDataAuthorised,
    loadTables,
    putTablesIntoSchemaItems,
    call,
    callAsync,
    registerCall,
    registerCalls,
    removeCall,
    removeCalls,
    getGlobalState,
    setGlobalState,
    getStateValue,
    getStateArrayValue,
    getStateFirstValue,
    registerforStateChanges,
    removeStateChanges,
    dumpDataType,
    isStoredItem,
    getPropertyArrayFromItemArray,
    getPropertiesArrayFromItemArray,
    getPropertyArrayFromItemArrayUnique,
    isItemType,
    itemWillSend,
    typeWillRetrieve,
    itemIsSent,
    typeIsRetrieved,
    typeRetrieveFailed,
    itemSendSucceeed,
    itemSendFailed,
    sendsInProgress,
    sendsToGo,
    lastSentMessage,
    itemsToSendMessageList,
    lastProcessMessage,
    processPercentComplete,
    flushStatusMessages,
    toSendMessages,
    completedMessages,
    failedMessages,
    registerOnProcessChange,
    removeOnProcessChange,
    dumpCompletedActions,
    dumpToDo,
    isUUID,
    dateStripTimezone,
    dateAddTimezone,
    selectedConsentNumber,
    initializeProcessStatusManager,
} = addStore('global')

initializeProcessStatusManager()